blank_issues_enabled: false
contact_links:
  - name: ğŸ“Œ ì¼ë°˜ ì œì•ˆ/ì•„ì´ë””ì–´
    url: https://github.com/ShrimpLake/shrimplake-core/discussions
    about: ê¸°íƒ€ ì•„ì´ë””ì–´ë‚˜ ë…¼ì˜ê°€ í•„ìš”í•œ ë‚´ìš©ì€ Discussions íƒ­ì„ í™œìš©í•´ì£¼ì„¸ìš”.

